---
- name: Install required system packages
  become: true
  ansible.builtin.package:
    name:
      - apt-transport-https
      - apache2
      - openssh-server
      - ca-certificates
      - curl
      - software-properties-common
      - virtualenv
    state: latest
    update_cache: true

- name: Add Docker GPG apt Key
  become: true
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
  retries: 3
  delay: 3
  register: result
  until: result is not failed

- name: Add Docker Repository
  become: true
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu focal stable
    state: present

- name: Update apt and install Docker packages
  become: true
  ansible.builtin.package:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-compose
    state: latest
    update_cache: true

- name: Add user to the Docker group
  become: true
  user:
    name: "{{ ansible_user }}"
    groups: docker
    append: yes
