---
- name: Configure VMs
  hosts: all
  roles:
    - packages
  tasks:
    - name: Install local ssh key
      ansible.posix.authorized_key:
        user: "{{ ansible_user }}"
        state: present
        key: "{{ lookup('file', '/home/tassadar/.ssh/framework.pub') }}"
